### PR TITLE
Extend FFFT to composite lengths

### PR DESCRIPTION
**Pull request by mrwojtek**
Extends power of two FFFT algorithm to generic composite length. The prime cases are delegated to `openfermioncirq.bogoliubov_transform()` function.

### CODE REVIEW

**Comment by babbush** [comment]
I think there is a question about how comfortable we are adding sympy as a dependency. @kevinsung @Strilanc what are your thoughts about this? I see you are using it for prime factoring. @Strilanc do you have any ideas about a quick way one might perform factoring without sympy. Note that in practice we will not need to factor particularly large numbers here so even a rather hacky routine for factoring might be fine.

**Comment by mrwojtek** [comment]
I was also hesitant to introduce sympy dependency but my main motivation for doing that was https://github.com/quantumlib/Cirq/issues/393, which imply depending on sympy in the future indirectly through Cirq anyway.

Implementing number factoring for the range we care about is pretty simple, O(sqrt(n)) algorithm should fit in 3 or 4 lines of Python code. It's not a problem to do that at all.

@Strilanc, @kevinsung what do you think?

**Comment by mrwojtek** [comment]
I need to update details in documentation still, should be ready for re-review soon.

**Comment by mrwojtek** [comment]
OK, this is now ready for review! I started to wonder if this PR shouldn't be actually dropped because of minor benefit it could give to NISQ algorithms. On the other hand, it is a generalization of the power-of-2 FFFT.

There still issue raised by @babbush of weather we should add sympy dependency or do the prime number factoring ourselves (which is just a few lines of python code most likely).

**Pull request merged**
