### PR TITLE
Define _apply_unitary_to_tensor_ for ZZ, XXYY, YXXY, CXXYY, CYXXY, DoubleExcitation, CombinedDoubleExcitation

### PR DESCRIPTION
**Pull request by Strilanc**
A benchmark using CXXYY improved from 4.87s to 0.62s (~8x better)
A benchmark using DoubleExcitation improved from 6.7s to 1.4s (~5x better)

### CODE REVIEW

**Comment by Strilanc** [comment]
Is there a reason the relative phases of DoubleExcitation rotate twice as fast as in CombinedDoubleExcitation?

**Comment by bryano** [comment]
@Strilanc IIRC I chose something arbitrary for `CombinedDoubleExcitation` because it wasn't clear which convention would ultimately be chosen and figured it would be a simple fix when the time came.

**Comment by Strilanc** [comment]
@bryano Please open an issue in those kinds of situations, so that the choice doesn't get lost to time.

**Comment by kevinsung** [comment]
@Strilanc I'll finish this up

**Pull request merged**
