### PR TITLE
Exponent of QubitOperator to cirq

### PR DESCRIPTION
**Pull request by xabomon**
Hi all,

I went ahead and coded functions that generate circuits of exp(-i \theta P) where P is a Pauli operator. This covers issue #368 .
Currently, only supports QubitOperator but I can easily extend it to Pauli_String class.

Regarding coding style and test I followed the structure of OpenFermion but I tried to copy some of the structures that I saw in OpenFermion-Cirq, feel free to comment/review this too.

There was also the open question whether this was better suited for Cirq or OpenFermion-Cirq. To me, OpenFermion-Cirq seems more reasonble than Cirq as this functionality belongs to the applications of Cirq and not to its core.

Best,
Xavi

### CODE REVIEW

**Comment by kevinsung** [comment]
Please implement your algorithm as a `TrotterAlgorithm` (see `trotter/algorithms/` for examples).

**Comment by xabomon** [comment]
Hi @kevinsung ,

I have a concern about implementing this as a `TrotterAlgorithm`.

One of the functions takes a QubitOperator with a single Pauli string and generates the unitary `exp(i\theta P)`. Somehow I feel that this can be independent of the Trotter algorithm.

Of course, when the QubitOperator becomes a sum of Pauli strings then Trotter algorithm seems reasonable.

What are your thoughts on this?

Best,
Xavi

**Comment by xabomon** [comment]
My apologies for the gazillion commits! CI was giving me a hard time.

Best,
Xavi

**Comment by kevinsung** [comment]
We shouldn't have a special case for when the QubitOperator is a single term.

**Comment by xabomon** [comment]
A related PR in Cirq is opened to implement exponents of PauliSum objects:
https://github.com/quantumlib/Cirq/issues/3169

I will close this PR as it is outdated.

**Pull request closed without merging**
