### PR TITLE
Update authors list

### PR DESCRIPTION
**Pull request by kevinsung**

### CODE REVIEW

**Comment by kevinsung** [comment]
I just added the remaining authors at the end according to the order listed in "Contributors". My personal opinion is that we should just remove the Authors section because people can just see who contributed.

**Comment by babbush** [comment]
@kevinsung I agree with your suggestion. Let's just remove the authors list from OpenFermion-Cirq.

**Comment by babbush** [comment]
@kevinsung why did you close this rather than just remove the authors as we suggested? Will you do that in another PR?

**Comment by kevinsung** [comment]
Yes, I'll do it in another PR.

**Pull request closed without merging**
