### PR TITLE
added num_qubits method to excitation gates

### PR DESCRIPTION
**Pull request by bryano**
This is needed for compliance with the current dev version of Cirq.

### CODE REVIEW

**Comment by ncrubin** [comment]
@bryano Looks like tests and coverage are failing.  Is this PR still live?  sorry for the delay.

**Comment by bryano** [comment]
I don't understand why the coverage is failing. It passes on my machine, and there are tests that cover the lines that it says are uncovered. Weirder still is that it says that the _testing_ lines are uncovered.

**Comment by babbush** [comment]
coveralls has been known to be glitchy. We can certainly force-merge your PR over coveralls' objections if that is the only issue.

**Comment by bryano** [comment]
My understanding is that OpenFermion-Cirq doesn't even use coveralls.

**Comment by babbush** [comment]
Oh crap I wasn't actually paying any attention to which PR this is (or what repo its in) and somehow assumed it was on OpenFermion not OpenFermion-Cirq. You are of course correct. Maybe @Strilanc has some ideas about what's going on. Still, we can force-merge over the coverage check if that's the main problem.

**Comment by bryano** [comment]
There does seem to be one non-coverage test failing, but I can't replicate it on my machine.

**Comment by ncrubin** [comment]
This is failing tests as well.  Not just coverage.

**Comment by bryano** [comment]
I replicated the issue. The problem is that Travis runs the tests using v0.4.0 of Cirq. The (breaking) changes to Cirq that this PR is meant to reconcile with came after that tag.

What's been decided about what version of Cirq the master branch of OpenFermion-Cirq should be compatible with?

**Comment by Strilanc** [comment]
This is obsoleted by https://github.com/quantumlib/OpenFermion-Cirq/pull/334

**Comment by Strilanc** [comment]
Sorry for not giving you the heads up I was working on getting it synced.

**Pull request closed without merging**
