### PR TITLE
Minor improvement to duration checks

### PR DESCRIPTION
**Pull request by idk3**
Put `duration` checks into its own OpenFermion-Cirq function.

### CODE REVIEW

**Comment by kevinsung** [comment]
I'm not sure about this change ... it seems to be implying that there is a unit called "duration" which is equal to half of a rad. That sounds like nonsense honestly. In reality we are defining "duration" on an ad hoc basis, which just happens to have the same formula in the cases implemented so far.

**Comment by idk3** [comment]
I'd say degrees and rads make less sense when it comes to gates defined by evolution!

I'm trying to better understand your concern though - is it that we have to (artificially?) align or rescale the generator of evolution to make this work? I think that might actually be net helpful, and we already do it for e.g. XXYYGate. Having both `exp(-i rads (X⊗X + Y⊗Y) / 4)` and `exp(-i t (X⊗X + Y⊗Y) / 2)` gives different consistent definitions that are more approachable to different people.

**Comment by bryano** [comment]
Maybe call it `half_rads` instead of `duration`? Then in the documentation, we can make clear that "half_rads" is what most people what think of as theta.

**Comment by babbush** [comment]
@kevinsung its been a month: what's going on with this PR? Should we merge it or close it or are we waiting for something to happen?

**Comment by kevinsung** [comment]
Closing for now, since this will be obsoleted when we get rid of half_turns (see https://github.com/quantumlib/Cirq/issues/865)

**Pull request closed without merging**
