### PR TITLE
Delete ZZGate and add ofc.Rzz which is exp(-i Z⊗Z rads)

### PR DESCRIPTION
**Pull request by kevinsung**
It's in Cirq now.

### CODE REVIEW

**Comment by Strilanc** [comment]
Note that the one in cirq doesn't have the same global phase convention, and doesn't have a `duration` argument. Do you still want to delete it? Maybe add an `Rzz` method as an alternative?

**Comment by kevinsung** [comment]
Sure, we can add an `Rzz` alternative. I think we should rename `duration` to `rads`.

**Comment by kevinsung** [comment]
@Strilanc cirq.ZZPowGate is not in the latest dev release

**Comment by Strilanc** [comment]
@viathor is creating a new dev release today, so that will be fixed quite soon

**Comment by viathor** [comment]
0.4.0.dev4220181119201229 is out.

**Comment by kevinsung** [comment]
Obsoleted by #316

**Pull request closed without merging**
